LMSproject/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include


import app1_users #//
import app2_courses

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app1_users.urls') ),
    path('courses/', include('app2_courses.urls' )),

]



# //  set media files setting
# from django.conf import settings
# from django.conf.urls import static

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
#     )

# // for production keep the media in a separate folder


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app2_courses/urls.py
from django.urls import path # //

from . import views

app_name = 'app2_courses'

urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.Subject_List_View.as_view(), name='subject_list'),
    # slug used , great

    path('<str:standard>/<slug:slug>', views.LessonListView.as_view(), name='lesson_list'),
    # Note that to uniquely track the page we are using two slugs 1 for standard and another for the slug i.e lesson


    # path('user_logout', views.user_logout, name='user_logout'),

    path('<str:standard>/<str:subject>/<slug:slug>', views.LessonDetailView.as_view(), name='lesson_detail'),
    

    # //CRUD new lesson add
    # \// modify the slug
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    #  / is important between

    path('<str:standard>/<str:subject>/<str:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),


    path('<str:standard>/<str:subject>/<str:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),




     
]

app2_courses/models.py
from django.db import models

# //to slugify and make url endpoints based on chapters
from django.template.defaultfilters import slugify
from django.urls import reverse
# //user model
from django.contrib.auth.models import User
import os

# for redirection
from django.urls import reverse

# Create your models here.

class Standard(models.Model):
    name = models.CharField(max_length = 100, unique = True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=1000, blank = True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


# // code for saving images to media as earlier
# rename the file and store
def save_subject_images(instance, filename):
    upload_to = 'images/'
    # // this is a folder, make a note of folder vs a file
    ext = filename.split('.')[-1]

    if(instance.subject_id):
        # filename = 'User_profile_picture/{}.{}'.format(instance.user.username, ext)
         filename = 'Subject_pictures/{}.{}'.format( instance.subject_id, ext )
        #  using subject_id as it will be unique 

    return os.path.join(upload_to, filename) 
    # what it does? 


class Subject(models.Model):

    subject_id = models.CharField(max_length = 50, unique=True)
    name = models.CharField(max_length = 100)
    slug = models.SlugField(null =True, blank=True)

    standard = models.ForeignKey(Standard, on_delete = models.CASCADE, related_name = 'subjects')
    #  one to many rlation between standard  and subjects as a standard can have many subjects

    image = models.ImageField(upload_to = save_subject_images, blank=True, verbose_name='subject Image')
    description = models.TextField(max_length = 200, blank=True)


    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)

        super().save(*args, **kwargs)


# /Lesson for 


def saved_lesson(instance, filename):
    upload_to = 'images/'
    # // this is a folder, make a note of folder vs a file
    ext = filename.split('.')[-1]

    if(instance.lesson_id):
        # filename = 'User_profile_picture/{}.{}'.format(instance.user.username, ext)
        filename = 'lesson_files/{}/{}.{}'.format( instance.lesson_id, instance.lesson_id, ext )
        #  using subject_id as it will be unique 

        if(os.path.exists(filename)):
            new_name = str(instance.lesson_id) + str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.lesson_id, new_name, ext)

    return os.path.join(upload_to, filename) 


class Lesson(models.Model):
    lesson_id = models.CharField(max_length= 100, unique=True)
    Standard  =models.ForeignKey(Standard, on_delete=models.CASCADE)
    # created_by=models.ForeignKey(User, on_delete=CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
# if user is deleted then all data created by it will also be deleted ??

    created_at = models.DateTimeField(auto_now_add  = True)

    subject =  models.ForeignKey(Subject, on_delete = models.CASCADE, related_name = "lessons")
    # a lesson can be connected to only one subject

    name = models.CharField(max_length = 100)
    position = models.PositiveSmallIntegerField(verbose_name = "chapter_no:")
    # position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    # chapter number

    slug = models.SlugField(null=True, blank=True)

    video = models.FileField(upload_to=saved_lesson, verbose_name = "video", blank=True, null=True)
    # verbose_name? significance ?
    ppt = models.FileField(upload_to = saved_lesson, verbose_name = 'ppt', blank = True, null=True)
    Notes = models.FileField(upload_to = saved_lesson, verbose_name = 'notes', blank = True, null=True)

    class Meta:
        ordering = ['position']
        # order based on position i.e chapter no;

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


    #  To redirect the user to lesson list after he updates the lessons
    def get_absolute_url(self):
        return reverse('app2_courses:lesson_list', kwargs={'slug':self.subject.slug, 'standard': self.Standard.slug})



#  comments and replies

class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson, null=True,  on_delete=models.CASCADE, related_name='comments')
    comm_name = models.CharField(max_length = 100, blank=True)

    author = models.ForeignKey(User, on_delete = models.CASCADE)
    body = models.TextField(max_length = 500)
    date_added = models.DateTimeField(auto_now_add = True)


    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-"+str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['date_added']  # latest first


class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name = 'replies')
    reply_body = models.TextField(max_length = 500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return "reply to "+ str(self.comment_name.comm_name)

app2_courses/forms.py
from django import forms
from .models import Lesson, Comment, Reply

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        # fields = ('__all__') # all the fields will be shown
        
        # specify the needed fields only
        fields = ('lesson_id','name', 'position', 'video', 'ppt', 'Notes')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {
            'body' : 'comment'
        }

        widgets={
            'body':forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"enter your comment here"}),
        }

        
    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     super(CommentForm, self).__init__(*args, **kwargs)

    # // no need after we add FormView in views of LessonDetail



class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)
        

        widgets = {
            'reply_body':forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10, 'placeholder':'enter your reply here' })
        }

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     super(ReplyForm, self).__init__(*args, **kwargs)

app2_courses/views.py
from django.shortcuts import render, HttpResponse


# // to work with the class based views
from django.views.generic import (TemplateView, DetailView, ListView, FormView)

# to work with the CRUD functionality
from django.views.generic import ( CreateView, UpdateView, DeleteView )

from .models import Standard, Subject, Lesson

# // for forms
from .forms import LessonForm , CommentForm, ReplyForm

from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.


# def index1(request):
#     return HttpResponse(" working? ")


class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'app2_courses/standard_list_view.html'


class Subject_List_View(DetailView):
    context_object_name = 'standards'
    #  context_object_name  keep this name as it is
    model = Standard
    template_name = 'app2_courses/subject_list_view.html'


class LessonListView(DetailView):
    context_object_name = 'subjects'
    #  context_object_name  keep this name as it is
    model = Subject
    template_name = 'app2_courses/lesson_list_view.html'


class LessonDetailView(DetailView, FormView):  # add FormView here to work with the comments and replies
    context_object_name = 'lessons'
    #  context_object_name  keep this name as it is
    model = Lesson
    template_name = 'app2_courses/lesson_detail_view.html'   

    # for comments and replies
    form_class = CommentForm
    second_form_class = ReplyForm



    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            # context['form'] = self.form_class(request=self.request)
            # this requires to change the __init__ function of reply form in forms.py

            context['form'] = self.form_class() # no need of request when we use the FormView

        if 'form2' not in context:
            # context['form2'] = self.second_form_class(request=self.request)
       # context['comments'] = Comment.objects.filter(id=self.object.id)

            context['form2'] = self.second_form_class()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            # form_class = self.get_form_class()
            form_class = self.form_class
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)


    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        # stay
        return reverse_lazy('app2_courses:lesson_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})



    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
        




#  CRUD part
class LessonCreateView(CreateView):
    form_class =  LessonForm
    context_object_name = 'subject'
    model = Subject
    template_name = 'app2_courses/lesson_create.html'


    # override the default form_valid function of the CreateView class as per our need
    # and store the inputs in our db


    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('app2_courses:lesson_list',
        kwargs={'standard':standard.slug, 'slug':self.object.slug})  # ??
    
    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

'''
    def form_valid(self, form, *args, **kwargs): 
        self.object = self.get_object()
        fm = form.save(commit = False)
        fm.created_by = self.request.user
        fm.standard = self.object.standard # foreign key relation with the standard
        # use fm.Standard
        # understand where to use the modelname and where to use the var name
        fm.subject = self.object
        fm.save()

        return HttpResponseRedirect(self.get_success_url() )  # define a function for get_success_url
'''


# updating

class LessonUpdateView(UpdateView):
    fields = ('name','position', 'video', 'ppt', 'Notes')
    model = Lesson
    template_name = 'app2_courses/lesson_update.html'
    context_object_name = 'lessons' #lessons ?? why not lesson


class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = 'lessons'
    template_name = 'app2_courses/lesson_delete.html'

    # once deleted where to redirect the user 

    def get_success_url(self):
        standard = self.object.Standard
        subject = self.object.subject #Standard caps subject small
        return reverse_lazy('app2_courses:lesson_list', kwargs={'standard':standard.slug, 'slug':subject.slug})

app2_courses/templates/app2_courses/lesson_create.html
{% extends "home.html" %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
{% csrf_token %}

<!-- {{form.as_p}} --> 
<!-- instead use the crispy forms -->

{{ form | crispy }}
<!-- form class is treated as form in html file -->

<input type="submit" name="" value="submit">
</form>

{% endblock  %}

app2_courses/templates/app2_courses/lesson_delete.html
{% extends "home.html" %}

{% block content %}

<h2> Are you sure you want to delete this?</h2>

<form method="post">
    {% csrf_token %}

    <input type="submit" value="delete">

    <a href="{% url 'app2_courses:lesson_detail' standard = lessons.Standard.slug subject = lessons.subject.slug slug=lessons.slug ">Delete the lesson [Confirm]</a>

</form>

{% endblock  %}

app2_courses/templates/app2_courses/lesson_detail_view.html
{% extends "home.html" %}

{% block content %}

{% block title %} {{lessons.name}} {% endblock %}

 Lesson Created on {{lessons.created_at}} by {{lessons.created_by}} 

<a
    href="{% url 'app2_courses:lesson_update'  standard=lessons.Standard.slug  subject=lessons.subject.slug slug=lessons.slug  %}">
    Update the Lesson
</a>
<!-- add link to take the user to the lesson update -->

<!-- don't ever forget to apply the migrations -->
<br>

<!-- for delete -->

<a
    href="{% url 'app2_courses:lesson_delete'  standard=lessons.Standard.slug  subject=lessons.subject.slug slug=lessons.slug  %}">
    Delete Lesson </a>

<h3>Comment Sectiom</h3>

<form method="post">
    <div class="form-group">
        {% csrf_token %}

        {{ form.as_p}}

        <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">

    </div>
</form>



<div class="row">
    {% for comment in lessons.comments.all %}

    <h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
    <p>{{comment.body}}</p>
    {% for reply in comment.replies.all %}

    <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
    <p>{{reply.reply_body}}</p>

    {% endfor %}
    <!-- form to post reply -->
    <form method="post">
        <input type="hidden" name="comment.id" value="{{comment.id}}">
        <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
        {% csrf_token %}
        {{form2.as_p}}
        <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">





        {% endfor %}
</div>

{% endblock %}

app2_courses/templates/app2_courses/lesson_list_view.html
{% extends "home.html" %}

{% block  content %}




{% for lesson in subjects.lessons.all %}
                
                      <h1>Chapter-{{lesson.position}}: {{lesson.name}}</h1>
                    
                      <a href="{% url 'app2_courses:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}" >
                      Get Lesson Details
                      </a>

{% endfor %}

<!-- to addd the new lesson, note the slug here -->
<a href="{% url 'app2_courses:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"> Create a new Lesson </a>
{% endblock  %}

app2_courses/templates/app2_courses/lesson_update.html
{% extends "home.html" %}

{% block content %}

{% comment %} provide forms here for updating {% endcomment %}

<form method="post">
    {% csrf_token %}

    {{form.as_p}}
    <!-- form , not forms -->

    <input type="submit" value="submit">
    <!-- No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model -->
    <!-- add some get_absolute_url method in the models or here -->

    <!-- also add button to cancel the update -->
    <!-- send back the user to earlier page -->

    <a href="{% url 'app2_courses:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %} ">cancel update</a>
</form>

{% endblock  %}

app2_courses/templates/app2_courses/standard_list_view.html
{% extends "home.html" %}



{% block content %}


<!-- {% for standard in standards %}
<div class="col-md-4 d-flex mb-5 justify-content-center">
  <div class="card card-std text-center" style="width: 20rem;">
    <div class="card-body text-center">
      <h4 class="card-title" style="color:#ff5722;">{{standard.name}}</h4>
     
    </div>
  </div>
</div>
{% endfor %} -->

{% for standard in standards %}
<!-- note s is small of standards it's coming from context_object_name = 'standards' in the views.py -->

<h2>{{standard.name}} </h2>
<!-- put in anchor tag for navigation and to make it uable with the slug -->
<!-- provide href to the subject_list_view for the respective standard -->

<!-- <a href="#"> {{standard.name}} </a> -->
<a href="{% url 'app2_courses:subject_list' slug=standard.slug %}"> Get the subjects </a>
<!-- we have predefined the slug in models of each table -->

{% endfor %}


{% endblock  %}

app2_courses/templates/app2_courses/subject_list_view.html
{% extends "home.html" %}

{% block  content %}

<h1>subjects for this standard</h1>

{% for subject in standards.subjects.all  %}

{{subject.name}}

<!-- provide slug here -->
<a href="{% url 'app2_courses:lesson_list' slug=subject.slug standard=standards.slug %}"> Get the Lessons </a>
<!-- Note here that we have to provide two slugs here 1 for standard and one for the subject -->
<br>

<p>{{subject.description | truncatechars:75}}</p> <br>
{% endfor %}

{% endblock  %}