LMSproject/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include


import app1_users #//
import app2_courses

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app1_users.urls') ),
    path('courses/', include('app2_courses.urls' )),

]



# //  set media files setting
# from django.conf import settings
# from django.conf.urls import static

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT
#     )

# // for production keep the media in a separate folder


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

app2_courses/urls.py
from django.urls import path # //

from . import views

app_name = 'app2_courses'

urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.Subject_List_View.as_view(), name='subject_list'),
    # slug used , great

    path('<str:standard>/<slug:slug>', views.LessonListView.as_view(), name='lesson_list'),
    # Note that to uniquely track the page we are using two slugs 1 for standard and another for the slug i.e lesson


    # path('user_logout', views.user_logout, name='user_logout'),

    path('<str:standard>/<str:subject>/<slug:slug>', views.LessonDetailView.as_view(), name='lesson_detail'),
    

    # //CRUD new lesson add
    # \// modify the slug
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    #  / is important between

    path('<str:standard>/<str:subject>/<str:slug>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),


    path('<str:standard>/<str:subject>/<str:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete'),




     
]

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <div class="container">
        <div class="jumbotron">
            <a href="{% url 'index' %}"> Home </a>
            
            <!-- <a href="{% url 'user_login' %}"> Login </a> -->
            <a href="{% url 'register' %}"> Register </a>


            <!-- show logout option only when logged in -->
            {% if user.is_authenticated %}
            <a href="{% url 'user_logout' %}"> Logout</a>
            {% else %}
            <a href="{% url 'user_login' %}"> Login </a>
            {% endif %}

            <a href="{% url 'admin:index' %}"> Admin Page </a>
            <a href="{% url 'app2_courses:standard_list' %}"> Standards  </a>


            <!-- <a href=" url 'courses:standard_list' "> Standards  </a> -->
            <!-- when using the courses:standard_list, gives error as -->
            <!-- django.urls.exceptions.NoReverseMatch: 'courses' is not a registered namespace -->

             
            <!-- we have used the namespaces here in the redirections -->

            <h1>Welcome on the Home Page </h1>

            <!-- for extend purposes -->
            {% block content %} 

            {% endblock %}

        </div>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
   

    
  </body>
</html>